### PR TITLE
a lot....

### PR DESCRIPTION
**Pull request by mlanci**
added new route for /game/[id]/route.ts to pull specific game IDs

Went back to "URL params" not query params for this.. react was bitching about passing a body in an HTTP GET request..

Added page for /game/[id]/page.tsx

### CODE REVIEW

**Comment by mlanci** [comment]
Putting my stamp of approval on my changes - not sure what has to change on the deployment side though.. I need to figure out if I can add some checks locally that matches with whatever vercel is checking...

@c-stone  if you figure it out, and it doesn't break anything.. your good to merge this one!

**Comment by c-stone** [comment]
Looking through it now and there are a lot of type errors. We will need to add proper types to all variables. It's possible to catch some of the build errors locally by running `pnpm run build`.

**Comment by mlanci** [comment]
or lets just not use typescript HAHAA. no i can fix those then if thats the solution

**Comment by mlanci** [comment]
So I fixed a few linting problems but then the rest I'm not exactly sure how to solve..

For example - I don't know what the modules object will look like in the response yet.. while this forces me to think about it I really just have no idea and may move on to some different feature.. so I decided to add a ignore eslint at the top of the files that it was complaining about.

We either go to regular js.. or go abck and fix the strongly typed things im missing later.. or just ignore eslint LOL

**Comment by mlanci** [comment]
Approved.

**Review by c-stone — APPROVED** [review]

**Pull request merged**
